create table books (
  id int primary key generated by default as identity,
  user_id int not null references users on delete cascade,
  title text not null,
  author text not null,
  finish_date date not null,
  format text not null,
  location text,
  insert_time timestamptz not null default now(),
  update_time timestamptz not null default now()
);
